export const REGISTER='REGISTER'

export const ADD_CUSTOMER='ADD_CUSTOMER'
export const FETCH_CUSTOMER_FAILURE='FETCH_CUSTOMER_FAILURE'
export const USER_INPUT_CHANGE="USER_INPUT_CHANGE"


export const FETCH_USERS_REQUEST = 'FETCH_USERS_REQUEST'
export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS'
export const FETCH_USERS_FAILURE = 'FETCH_USERS_FAILURE'
